### ISSUE TITLE
Failed to launch e2e testing on Windows

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#180]
**Issue description**
On Windows, `npm run webdriver-update` will update webdriver binaries but **update-config.json** is not downloded in the update. This also happens in the upstream repo [angular-seed](https://github.com/mgechev/angular-seed).  However, for zephyrjs-ide, e2e testing fails to launch while angular-seed can pass e2e testing.

update-config.json is not missing on Linux during downloading webdriver binaries. So there is no such problem on Linux.
`npm run e2e.ci` is not affected by this problem on all platforms,

**Current behavior**
update-config.json is missing when update webdriver on Windows and e2e testing fails to launch.

**Expected behavior**
No testing error.

**Steps to reproduce**
1. `git clone https://github.com/01org/zephyrjs-ide`
2. `cd zephyrjs-ide && npm install`
3. `npm run webdriver-update`
4. In command prompt 1: `npm run serve.e2e`. Then in command prompt 2: `npm run e2e`:
```

> zephyrjs-ide@0.19.0-alpha e2e C:\Workspace\Work\week31\zephyrjs-ide
> protractor

[17:52:01] I/launcher - Running 1 instances of WebDriver
[17:52:01] I/direct - Using ChromeDriver directly...
[17:52:01] E/direct - Error code: 135
[17:52:01] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[17:52:01] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at IError (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\exitCodes.js:6:1)
    at ProtractorError (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\exitCodes.js:11:9)
    at BrowserError (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\exitCodes.js:52:9)
    at Direct.getNewDriver (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\driverProviders\direct.js:63:31)
    at Runner.createBrowser (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Workspace\Work\week31\zephyrjs-ide\node_modules\protractor\node_modules\q\q.js:556:49
[17:52:01] E/launcher - Process exited with error code 135
```

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.19.0-alpha / 18c7815`

**Comment by qiuzhong** [comment]
It turns out that the webdriver update sometimes gets this warning:
```
(node:8204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to make Github request, rate limit reached.
```
Then it fails to download update-config.json. However, this doesn't always happen. It's easily happen when you `npm run webdriver-update` frequently. This should be a problem from [webdriver-manager](https://github.com/angular/webdriver-manager/issues/216) and not an IDE issue.
